version: '3.8' 

services:
  backend:
    volumes:
      - static:/static
      - .:/application
    env_file:
      - ./.env/.env
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      python3 ./application/manage.py migrate && python3 ./application/manage.py collectstatic --noinput && python3 manage.py createsuperuser && gunicorn app.wsgi -b 0.0.0.0:8080
      "
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./static:/static
volumes:
  static:
  app: