# version: '3.8'

services:
  web:
    build: .
    command: ./init_superuser.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin  
      - DJANGO_SUPERUSER_PASSWORD=admin  
      - DJANGO_SUPERUSER_EMAIL=admin@example.com