# Generated by Django 5.0.7 on 2024-07-18 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=256, verbose_name='nombre de la organización')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha del diagnostico')),
                ('gr', models.BigIntegerField(default=0, verbose_name='gestion de riesgos')),
                ('ga', models.BigIntegerField(default=0, verbose_name='gestion de activos')),
                ('gia', models.BigIntegerField(default=0, verbose_name='gestion de identidad y acceso')),
                ('gav', models.BigIntegerField(default=0, verbose_name='gestion de amenazas y vulnerabilidades')),
                ('cea', models.BigIntegerField(default=0, verbose_name='conciencia del estado actual')),
                ('iic', models.BigIntegerField(default=0, verbose_name='intercambio de informacion y comunicaciones')),
                ('ri', models.BigIntegerField(default=0, verbose_name='respuesta a incidentes')),
                ('gde', models.BigIntegerField(default=0, verbose_name='gestion de dependencias externas')),
                ('cp', models.BigIntegerField(default=0, verbose_name='capacitacion del personal')),
                ('gpc', models.BigIntegerField(default=0, verbose_name='gestion de programa de ciberseguridad')),
                ('total', models.BigIntegerField(default=0, verbose_name='puntaje total')),
                ('id_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organisation')),
            ],
        ),
    ]
